/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AllocationRouteImport } from './routes/allocation'
import { Route as BackordersRouteImport } from './routes/backorders'
import { Route as PickListsRouteImport } from './routes/pick-lists'
import { Route as PickingRouteImport } from './routes/picking'
import { Route as SalesOrdersRouteImport } from './routes/sales-orders'
import { Route as WavePlanningRouteImport } from './routes/wave-planning'
import { Route as WaveReleaseRouteImport } from './routes/wave-release'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AllocationRoute = AllocationRouteImport.update({
  id: '/allocation',
  path: '/allocation',
  getParentRoute: () => rootRouteImport,
} as any)
const BackordersRoute = BackordersRouteImport.update({
  id: '/backorders',
  path: '/backorders',
  getParentRoute: () => rootRouteImport,
} as any)
const PickListsRoute = PickListsRouteImport.update({
  id: '/pick-lists',
  path: '/pick-lists',
  getParentRoute: () => rootRouteImport,
} as any)
const PickingRoute = PickingRouteImport.update({
  id: '/picking',
  path: '/picking',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesOrdersRoute = SalesOrdersRouteImport.update({
  id: '/sales-orders',
  path: '/sales-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const WavePlanningRoute = WavePlanningRouteImport.update({
  id: '/wave-planning',
  path: '/wave-planning',
  getParentRoute: () => rootRouteImport,
} as any)
const WaveReleaseRoute = WaveReleaseRouteImport.update({
  id: '/wave-release',
  path: '/wave-release',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/allocation': typeof AllocationRoute
  '/backorders': typeof BackordersRoute
  '/pick-lists': typeof PickListsRoute
  '/picking': typeof PickingRoute
  '/sales-orders': typeof SalesOrdersRoute
  '/wave-planning': typeof WavePlanningRoute
  '/wave-release': typeof WaveReleaseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/allocation': typeof AllocationRoute
  '/backorders': typeof BackordersRoute
  '/pick-lists': typeof PickListsRoute
  '/picking': typeof PickingRoute
  '/sales-orders': typeof SalesOrdersRoute
  '/wave-planning': typeof WavePlanningRoute
  '/wave-release': typeof WaveReleaseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/allocation': typeof AllocationRoute
  '/backorders': typeof BackordersRoute
  '/pick-lists': typeof PickListsRoute
  '/picking': typeof PickingRoute
  '/sales-orders': typeof SalesOrdersRoute
  '/wave-planning': typeof WavePlanningRoute
  '/wave-release': typeof WaveReleaseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/allocation'
    | '/backorders'
    | '/pick-lists'
    | '/picking'
    | '/sales-orders'
    | '/wave-planning'
    | '/wave-release'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/allocation'
    | '/backorders'
    | '/pick-lists'
    | '/picking'
    | '/sales-orders'
    | '/wave-planning'
    | '/wave-release'
  id:
    | '__root__'
    | '/'
    | '/allocation'
    | '/backorders'
    | '/pick-lists'
    | '/picking'
    | '/sales-orders'
    | '/wave-planning'
    | '/wave-release'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AllocationRoute: typeof AllocationRoute
  BackordersRoute: typeof BackordersRoute
  PickListsRoute: typeof PickListsRoute
  PickingRoute: typeof PickingRoute
  SalesOrdersRoute: typeof SalesOrdersRoute
  WavePlanningRoute: typeof WavePlanningRoute
  WaveReleaseRoute: typeof WaveReleaseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/allocation': {
      id: '/allocation'
      path: '/allocation'
      fullPath: '/allocation'
      preLoaderRoute: typeof AllocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backorders': {
      id: '/backorders'
      path: '/backorders'
      fullPath: '/backorders'
      preLoaderRoute: typeof BackordersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pick-lists': {
      id: '/pick-lists'
      path: '/pick-lists'
      fullPath: '/pick-lists'
      preLoaderRoute: typeof PickListsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/picking': {
      id: '/picking'
      path: '/picking'
      fullPath: '/picking'
      preLoaderRoute: typeof PickingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-orders': {
      id: '/sales-orders'
      path: '/sales-orders'
      fullPath: '/sales-orders'
      preLoaderRoute: typeof SalesOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wave-planning': {
      id: '/wave-planning'
      path: '/wave-planning'
      fullPath: '/wave-planning'
      preLoaderRoute: typeof WavePlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wave-release': {
      id: '/wave-release'
      path: '/wave-release'
      fullPath: '/wave-release'
      preLoaderRoute: typeof WaveReleaseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AllocationRoute: AllocationRoute,
  BackordersRoute: BackordersRoute,
  PickListsRoute: PickListsRoute,
  PickingRoute: PickingRoute,
  SalesOrdersRoute: SalesOrdersRoute,
  WavePlanningRoute: WavePlanningRoute,
  WaveReleaseRoute: WaveReleaseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
