/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AllocationRouteImport } from './routes/allocation'
import { Route as BackordersRouteImport } from './routes/backorders'
import { Route as SalesOrdersRouteImport } from './routes/sales-orders'
import { Route as WavePlanningRouteImport } from './routes/wave-planning'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AllocationRoute = AllocationRouteImport.update({
  id: '/allocation',
  path: '/allocation',
  getParentRoute: () => rootRouteImport,
} as any)
const BackordersRoute = BackordersRouteImport.update({
  id: '/backorders',
  path: '/backorders',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesOrdersRoute = SalesOrdersRouteImport.update({
  id: '/sales-orders',
  path: '/sales-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const WavePlanningRoute = WavePlanningRouteImport.update({
  id: '/wave-planning',
  path: '/wave-planning',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/allocation': typeof AllocationRoute
  '/backorders': typeof BackordersRoute
  '/sales-orders': typeof SalesOrdersRoute
  '/wave-planning': typeof WavePlanningRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/allocation': typeof AllocationRoute
  '/backorders': typeof BackordersRoute
  '/sales-orders': typeof SalesOrdersRoute
  '/wave-planning': typeof WavePlanningRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/allocation': typeof AllocationRoute
  '/backorders': typeof BackordersRoute
  '/sales-orders': typeof SalesOrdersRoute
  '/wave-planning': typeof WavePlanningRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/allocation' | '/backorders' | '/sales-orders' | '/wave-planning'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/allocation' | '/backorders' | '/sales-orders' | '/wave-planning'
  id:
    | '__root__'
    | '/'
    | '/allocation'
    | '/backorders'
    | '/sales-orders'
    | '/wave-planning'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AllocationRoute: typeof AllocationRoute
  BackordersRoute: typeof BackordersRoute
  SalesOrdersRoute: typeof SalesOrdersRoute
  WavePlanningRoute: typeof WavePlanningRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/allocation': {
      id: '/allocation'
      path: '/allocation'
      fullPath: '/allocation'
      preLoaderRoute: typeof AllocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backorders': {
      id: '/backorders'
      path: '/backorders'
      fullPath: '/backorders'
      preLoaderRoute: typeof BackordersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-orders': {
      id: '/sales-orders'
      path: '/sales-orders'
      fullPath: '/sales-orders'
      preLoaderRoute: typeof SalesOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wave-planning': {
      id: '/wave-planning'
      path: '/wave-planning'
      fullPath: '/wave-planning'
      preLoaderRoute: typeof WavePlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AllocationRoute: AllocationRoute,
  BackordersRoute: BackordersRoute,
  SalesOrdersRoute: SalesOrdersRoute,
  WavePlanningRoute: WavePlanningRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
